"""
Discrepancy explanation endpoint.

POST /explain
    Body: { "discrepancy_ids": [1, 2, 3] }
    Returns a plain-language explanation generated by OpenAI.

This is a backend-only endpoint.  The OpenAI API key never leaves the server.
The LLM is used solely for explanation — it never decides whether records
match (that is done deterministically by app/reconcile.py).
"""

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.dependencies import get_current_user
from app.database import get_db
from app.models import User, Discrepancy
from app.services.explain import explain_discrepancies, ExplainError

router = APIRouter(prefix="/explain", tags=["explain"])


@router.post("")
async def explain(
    body: dict,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Explain one or more discrepancies identified by ID.

    Only discrepancies belonging to the authenticated user can be explained.
    Returns a structured explanation with recommended action, severity, and
    confidence.
    """
    discrepancy_ids = body.get("discrepancy_ids", [])
    if not isinstance(discrepancy_ids, list) or not discrepancy_ids:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="Provide a non-empty list of discrepancy_ids (integers).",
        )

    # Validate every entry is a positive integer.
    if not all(isinstance(i, int) and i > 0 for i in discrepancy_ids):
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="All discrepancy_ids must be positive integers.",
        )

    # De-duplicate while preserving order.
    discrepancy_ids = list(dict.fromkeys(discrepancy_ids))

    # Fetch discrepancies scoped to the current user.
    result = await db.execute(
        select(Discrepancy).where(
            Discrepancy.user_id == current_user.id,
            Discrepancy.id.in_(discrepancy_ids),
        )
    )
    discrepancies = result.scalars().all()

    if not discrepancies:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No matching discrepancies found for the current user.",
        )

    # Check that all requested IDs were found (some may belong to other users).
    found_ids = {d.id for d in discrepancies}
    missing = set(discrepancy_ids) - found_ids
    if missing:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Discrepancy IDs not found or not accessible: {sorted(missing)}",
        )

    # Convert ORM objects to dicts for the service.
    disc_dicts = [
        {
            "discrepancy_type": d.discrepancy_type,
            "order_id": d.order_id,
            "payment_ref": d.payment_ref,
            "expected_amount": float(d.expected_amount) if d.expected_amount is not None else None,
            "actual_amount": float(d.actual_amount) if d.actual_amount is not None else None,
            "difference": float(d.difference) if d.difference is not None else None,
            "notes": d.notes,
        }
        for d in discrepancies
    ]

    try:
        explanation = await explain_discrepancies(disc_dicts)
    except ExplainError as e:
        # Return a clear 502 error — never crash, never leak internals.
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=str(e),
        ) from e

    return {
        "explanation": explanation.explanation,
        "recommended_action": explanation.recommended_action,
        "severity": explanation.severity,
        "confidence": explanation.confidence,
        "discrepancy_ids": discrepancy_ids,
    }
